set nocompatible              " required
set encoding=utf-8
filetype off                  " required

" Don't delete!
source $VIMRUNTIME/vimrc_example.vim

" *********************************************
" Vim settings
" *********************************************
syntax on
colorscheme molokai
"set guifont=Consolas:h12:cANSI
set cursorline "highlight current line
set hlsearch "highlight search
set viminfo+=n$HOME/.vim/.viminfo
set directory=$HOME/.vim/.tmp//,.
set undodir=$HOME/.vim/.tmp//,.
set noswapfile
set nobackup nowritebackup
set number "Show line numbers
set relativenumber "Relative line numbers with current line showing actual line number
set expandtab "Convert tabs to spaces
set tabstop=4 "Tab size
set backspace=indent,eol,start
"set nowrap
"" folding settings
set foldmethod=indent
set foldlevel=99

" split settings
set splitbelow
set splitright

" Remove arrow keys
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>
inoremap <Up> <Nop>
inoremap <Down> <Nop>
inoremap <Left> <Nop>
inoremap <Right> <Nop>

