return {
  dashboard = {
    alpha = false,
    dashboard = false,
  },
  lsp = {},
  testing = {
    neotest = false,
    nvim_test = true,
  },
  tree = {
    neotree = true,
    nvimtree = false,
  },
  autopairs = true,
  autotag = true,
  bufferline = false, -- Tabs at top, using winbar instead
  cmp = true,
  colorful_winsep = false, -- Stopped using because redraw flickers
  colorizer = true,
  comment = true,
  dap = true,
  eyeliner = true,
  gitsigns = true,
  harpoon = true,
  illuminate = true,
  indentline = true,
  java = true,
  lsplines = false,
  lualine = true,
  mason = true,
  metals = true,
  notify = true,
  nvim_lightbulb = false, -- Not currently using or setup
  nvim_scrollbar = true,
  pretty_fold = true,
  project = true,
  telescope = true,
  toggler = true,
  toggleterm = true,
  treesitter = true,
  twilight = false,
  winbar = true,
  whichkey = true,
  worktree = true,
}
