import = ["~/.config/alacritty/themes/dracula.toml"]
live_config_reload = true

[colors.primary]
background = "#000000"
foreground = "#f8f8f2"

[cursor]
thickness = 0.1

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "Cousine Nerd Font"
style = "Bold"

[font.italic]
family = "Cousine Nerd Font"
style = "Italic"

[font.normal]
family = "Cousine Nerd Font"
style = "Regular"

[[mouse.bindings]]
action = "Paste"
mouse = "Middle"

[selection]
save_to_clipboard = false

[window]
opacity = 1.0

[window.class]
instance = "alacritty"

[window.padding]
x = 4
y = 2
